name: Build

on:
  push:
    branches:
      - main


jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
          with:
            fetch-depth: 0
        - name: Prepare Environment
          run: |
            mkdir -p /home/runner/work/angular-17-crud-example/angular-17-crud-example/.scannerwork/.sonartmp
            chmod -R 777 /home/runner/work/angular-17-crud-example/angular-17-crud-example/.scannerwork
        - uses: sonarsource/sonarqube-scan-action@master
          env:
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
            SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        - name: Install SonarQube Scanner
          run: npm install -g sonar-scanner
        - name: SonarQube Scan
          run: sonar-scanner -Dsonar.projectKey=ltifour-ynov-frontend -Dsonar.projectName=ltifour-ynov-frontend -Dsonar.host.url=https://sonarqube-coe.westeurope.cloudapp.azure.com -Dsonar.login=${{ secrets.SONAR_TOKEN }}
